/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t ./public/models/conical-creature.glb
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF, mergeVertices } from 'three-stdlib'
import {  ShapeType, threeToCannon } from 'three-to-cannon'
import { useConvexPolyhedron } from '@react-three/cannon'
import { BufferGeometry, Mesh } from 'three'
import { ConvexPolyhedron } from 'cannon-es'

type GLTFResult = GLTF & {
  nodes: {
    Cone: THREE.Mesh
  }
  materials: {}
}

export function ConicalCreature(props: any) {
  const { nodes } = useGLTF('/models/conical-creature.glb') as GLTFResult

  const {shape} = threeToCannon(nodes.Cone, {type: ShapeType.HULL})!!

  const vertices = (shape as ConvexPolyhedron).vertices
  const faces = (shape as ConvexPolyhedron).faces

  const [ref] = useConvexPolyhedron(() => ({
    mass: 1, 
    rotation: [-1.68, 0, 0], 
    args: [vertices.map(vertex => vertex.toArray()), faces],
    ...props
  }))

  const geometry = mergeVertices(nodes.Cone.geometry)
  geometry.computeVertexNormals()

  return (
    <group dispose={null}>
      <mesh 
        ref={ref as React.RefObject<Mesh<BufferGeometry>>}
        geometry={geometry} 
        material={nodes.Cone.material}
        
      />
    </group>
  )
}

export default ConicalCreature

useGLTF.preload('/models/conical-creature.glb')
