/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t ./public/models/conical-creature.glb
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useBounds, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ShapeResult, ShapeType, threeToCannon } from 'three-to-cannon'
import { Triplet, useBox, useCompoundBody, useConvexPolyhedron, useCylinder, useSphere } from '@react-three/cannon'
import { BufferGeometry, Mesh } from 'three'
import { Box, ConvexPolyhedron, Shape, Vec3 } from 'cannon-es'

type GLTFResult = GLTF & {
  nodes: {
    Cone: THREE.Mesh
  }
  materials: {}
}

export function ConicalCreature(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/conical-creature.glb') as GLTFResult

  // const {shape, offset, orientation} = threeToCannon(nodes.Cone, {type: ShapeType.BOX})!!

  // const [ref, api] = useBox(() => ({mass: 0, rotation: [-1.68, 0, 0], args: (shape as Box).halfExtents.scale(2).toArray()}))

  const {shape} = threeToCannon(nodes.Cone, {type: ShapeType.HULL})!!

  const vertices = (shape as ConvexPolyhedron).vertices
  const faces = (shape as ConvexPolyhedron).faces

  const [ref, api] = useConvexPolyhedron(() => ({
    mass: 1, 
    rotation: [-1.68, 0, 0], 
    args: [vertices.map(vertex => vertex.toArray()), faces] 
  }))

  return (
    <group {...props} dispose={null}>
      <mesh 
        ref={ref as React.RefObject<Mesh<BufferGeometry>>}
        geometry={nodes.Cone.geometry} 
        material={nodes.Cone.material}
      />
    </group>
  )
}

export default ConicalCreature

useGLTF.preload('/models/conical-creature.glb')
