/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t ./public/models/quincey.glb
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { AnimationClip } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Mesh_2: THREE.Mesh
    body: THREE.Mesh
  }
  materials: {
    ['fur.001']: THREE.MeshStandardMaterial
    flesh: THREE.MeshStandardMaterial
    ['pupil.001']: THREE.MeshStandardMaterial
    fur: THREE.MeshStandardMaterial
  }
}

type ActionName = 'headAction'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Quincey(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/models/quincey.glb') as GLTFResult
  const { actions } = useAnimations<AnimationClip>(animations, group)
  return (
    <group ref={group as React.Ref<THREE.Group>} {...props} dispose={null}>
      <group name="Scene">
        <group name="Camera" position={[13.4, 1.08, 22.17]} rotation={[1.55, 0.01, -0.53]} scale={[2.66, 3, 2.66]}>
          <group name="Empty001" position={[-0.47, -3.38, -0.51]} rotation={[-1.53, -0.53, -0.04]} scale={[0.36, 0.38, 0.34]} />
        </group>
        <group name="Empty" position={[0.14, -1.35, -5.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.69} />
        <group name="head" position={[0, 1.83, 1.36]}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials['fur.001']} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.flesh} />
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials['pupil.001']} />
        </group>
        <mesh name="body" geometry={nodes.body.geometry} material={materials.fur} position={[0, -1.3, 1.36]} rotation={[Math.PI / 2, 0, 0]} scale={0.77} />
      </group>
    </group>
  )
}

export default Quincey
useGLTF.preload('/models/quincey.glb')
